### ISSUE TITLE
Project still requires mongo due to catbox-mongodb

### ISSUE THREAD

**Issue by BenjaminPrice** [YouHusam/hanx.js#3]
The project still uses catbox-mongodb. Is there an intention to change this to another catbox cache module to remove the mongo requirement or another caching plugin? If so, which? I'd recommend Redis personally.

**Comment by YouHusam** [comment]
@BenjaminPrice Yes, I will change it to Redis hopefully today

**Comment by YouHusam** [comment]
Uses Redis now
